{% set name = "deltalake" %}
{% set version = "0.25.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deltalake-{{ version }}.tar.gz
    sha256: 173e4b83fcff10f26474ae117161c3f2bdd5f44c30c20463c24b6b8b520e7656
  - url: https://raw.githubusercontent.com/delta-io/delta-rs/refs/tags/python-v{{ version }}/LICENSE.txt
    sha256: a25917a221b6184dcb9e0701f91dde42acc495f69958a84e2a5860a5c0f21ddd

build:
  number: 0
  # build failures on ppc64le
  skip: true                         # [ppc64le or (is_abi3 and not is_python_min)]
  python_version_independent: true   # [is_abi3]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2
    - make
    - cargo-bundle-licenses
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
    - m2-sed               # [win]
    - sed                  # [not win]
    # see https://aws.github.io/aws-lc-rs/requirements/linux.html
    - cmake                # [linux and not (x86_64 or aarch64)]
    - clang                # [linux and not (x86_64 or aarch64)]
    - libclang             # [linux and not (x86_64 or aarch64)]
  host:
    - python-abi3                    # [is_abi3]
    - python
    - maturin >=1,<2
    - pip
    - liblzma-devel  # [linux]
  run:
    - pyarrow-hotfix
    - python
    - pyarrow >=16,<19

test:
  requires:
    - pip <=24.1
    - abi3audit                      # [is_abi3]
  commands:
    - pip check
    - abi3audit $SP_DIR/deltalake/_internal.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}   # [unix and is_abi3]
    - abi3audit %SP_DIR%/deltalake/_internal.pyd -s -v --assume-minimum-abi3 {{ python_min }}      # [win and is_abi3]

about:
  home: https://github.com/delta-io/delta-rs
  summary: Native Delta Lake Python binding based on delta-rs with Pandas integration
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - python/THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dhirschfeld
    - charlesbluca
