{% set name = "deltalake" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deltalake-{{ version }}.tar.gz
  sha256: fbe4cccde0af14c6e30b62cc3dd09e9a46777e8fd8e375ec809a6bf4edea756c

build:
  script:
    # Taken from clangdev's recipe
    # https://github.com/conda-forge/clangdev-feedstock/blob/01fc5e3e0fc690db85151dcb3ff512e6aa876be7/recipe/build.sh#L51-L56
    # disable -fno-plt due to some GCC bug causing linker errors, see
    # https://github.com/llvm/llvm-project/issues/51205
    - export CFLAGS="$(echo $CFLAGS | sed 's/-fno-plt //g')"    # [ppc64le]
    - export CXXFLAGS="$(echo $CFLAGS | sed 's/-fno-plt //g')"  # [ppc64le]
    # license file inclusion by pip fails with 'Failed to write to *.dist-info/licenses/licenses/deltalake_license.txt'
    # since we are including it in the conda package separately, let's not do it with pip too
    - sed -i.bak '/^license =/d' pyproject.toml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2
    - make
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
    - m2-sed               # [win]
    - sed                  # [not win]
  host:
    - python
    - maturin >=1,<2
    - pip
    - liblzma-devel  # [linux]
  run:
    - arro3-core >=0.5.0
    - deprecated >=1.2.18
    - pyarrow-hotfix
    - python
    - pyarrow >=16,<19

test:
  commands:
    - pip check
  requires:
    - pip <=24.1

about:
  home: https://github.com/delta-io/delta-rs
  summary: Native Delta Lake Python binding based on delta-rs with Pandas integration
  license: Apache-2.0
  license_file: licenses/

extra:
  recipe-maintainers:
    - dhirschfeld
    - charlesbluca
