{% set name = "deltalake" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deltalake-{{ version }}.tar.gz
  sha256: c24ad4644b92d65dccf132b48c73e61bc07416b7a8b69e345c7f437217c44b2b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - maturin >=1,<2
    - make
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
  host:
    - python
    - maturin >=1,<2
    - pip
    - xz  # [linux]
  run:
    - pyarrow-hotfix
    - python
    - pyarrow >=8

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/delta-io/delta-rs
  summary: Native Delta Lake Python binding based on delta-rs with Pandas integration
  license: Apache-2.0
  license_file: licenses/

extra:
  recipe-maintainers:
    - dhirschfeld
    - charlesbluca
