{% set name = "deltalake" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deltalake-{{ version }}.tar.gz
  sha256: 79ab7d55f13e2a2ab118e54428e0a1fa31b17a078353c9fe13a5f35194de9521

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - maturin >=0.14,<0.15
    - make
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
    - xz  # [linux]
  run:
    - python
    - pyarrow >=8,<=12
    - typing-extensions  # [py<38]

test:
  imports:
    - deltalake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/delta-io/delta-rs
  summary: Native Delta Lake Python binding based on delta-rs with Pandas integration
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - charlesbluca
