{% set name = "deltalake" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deltalake-{{ version }}.tar.gz
  sha256: b3f896628876cc0465dccfb40cf76eaf977c6b551197e8e29da30f0457abb841

build:
  number: 0
  # build failures on ppc64le
  skip: true  # [ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2
    - make
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
    - m2-sed               # [win]
    - sed                  # [not win]
    # see https://aws.github.io/aws-lc-rs/requirements/linux.html
    - cmake                # [linux and not (x86_64 or aarch64)]
    - clang                # [linux and not (x86_64 or aarch64)]
    - libclang             # [linux and not (x86_64 or aarch64)]
  host:
    - python
    - maturin >=1,<2
    - pip
    - liblzma-devel  # [linux]
  run:
    - arro3-core >=0.5.0
    - deprecated >=1.2.18
    - pyarrow-hotfix
    - python
    - pyarrow >=16,<19

test:
  commands:
    - pip check
  requires:
    - pip <=24.1

about:
  home: https://github.com/delta-io/delta-rs
  summary: Native Delta Lake Python binding based on delta-rs with Pandas integration
  license: Apache-2.0
  license_file: python/LICENSE.txt

extra:
  recipe-maintainers:
    - dhirschfeld
    - charlesbluca
