{% set name = "deltalake" %}
{% set version = "0.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deltalake-{{ version }}.tar.gz
  sha256: 06c1b31ed7f820a7294544cde1d5eaceda08408f21eae0fc5c211e3758da27ba

build:
  script:
    # Taken from clangdev's recipe
    # https://github.com/conda-forge/clangdev-feedstock/blob/01fc5e3e0fc690db85151dcb3ff512e6aa876be7/recipe/build.sh#L51-L56
    # disable -fno-plt due to some GCC bug causing linker errors, see
    # https://github.com/llvm/llvm-project/issues/51205
    - export CFLAGS="$(echo $CFLAGS | sed 's/-fno-plt //g')"    # [ppc64le]
    - export CXXFLAGS="$(echo $CFLAGS | sed 's/-fno-plt //g')"  # [ppc64le]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2
    - make
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
  host:
    - python
    - maturin >=1,<2
    - pip
    - xz  # [linux]
  run:
    - pyarrow-hotfix
    - python
    - pyarrow >=16

test:
  commands:
    - pip check
  requires:
    - pip <=24.1

about:
  home: https://github.com/delta-io/delta-rs
  summary: Native Delta Lake Python binding based on delta-rs with Pandas integration
  license: Apache-2.0
  license_file: licenses/

extra:
  recipe-maintainers:
    - dhirschfeld
    - charlesbluca
